### ISSUE TITLE
Suggestion: for handling font icons

### ISSUE THREAD

**Issue by estelle** [OpenDyslexic/opendyslexic-chrome#49]
This likely has been thought of before, but just in case it hasn't, here goes:

To prevent "missing character" box icons from showing up when OpenDyslexic is used, add the `unicode-range` font-descriptor to the `@font-face` declaration, limiting the font to only the characters in the range.

```css
@font-face {
	font-family: 'opendyslexic';
	src: url('chrome-extension://__MSG_@@extension_id__/fonts/opendyslexic/OpenDyslexic-Bold.otf');
	font-weight: bold;
	font-style: normal;
        unicode-range: /* range of characters in OD */
}
```

`@font-face` supports the `unicode-range` font descriptor, which defines the range of characters for which a given face may be used. Adding `unicode-range` to the above with a value reflecting the available characters in openDislexic (OD) would mean a fallback font would be used for any characters not in the range. 

Using Hebrew as an example (source: CSS: The definitive guide), the following would limit using CMM-Ahuvah to only the small range of Hebrew characters:

``` css
@font-face {
    font-family: "CMM-Ahuvah";
    src: url("cmm-ahuvah.otf" format("opentype");
    unicode-range: U+590-5FF;
} 
```
